[profile.default]
src = "src"
test = "test"           #"audit-data/ProofOfCodes"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    'forge-std/=lib/forge-std/src/',
]

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"

[fuzz]
runs = 1000
seed = "0x0"

[invariant]
runs = 100
depth = 128
seed = "0x5"
fail_on_revert = true
show_metrics = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
